# Generated by Django 3.1.2 on 2020-11-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maakond', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vald',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vald', models.CharField(max_length=20)),
                ('maakond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakonnad.mk')),
            ],
        ),
        migrations.CreateModel(
            name='linn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linn', models.CharField(max_length=20)),
                ('vald_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maakonnad.vald')),
            ],
        ),
    ]
